apiVersion: v1
kind: ConfigMap
metadata:
  name: ckad-requester-config
data:
  appsettings.json: |-
    {
        "Worker": {
            "Websites": [
              {
                "Url": "http://plus-node-js-express-service:8080/plus?left=0.1&right=0.2",
                "NumberOfThreads": 10
              }
            ]
        }
    }